package una.airline.domain;
// Generated May 15, 2017 11:25:46 PM by Hibernate Tools 4.3.1

import java.util.LinkedList;
import java.util.List;

/**
 * Airplane generated by hbm2java
 */
public class Airplane implements java.io.Serializable {

    private String idAirplane;
    private Typeairplane typeairplane;
    private List<Flight> flights = new LinkedList<>();

    public Airplane() {
    }

    public Airplane(String idAirplane, Typeairplane typeairplane) {
        this.idAirplane = idAirplane;
        this.typeairplane = typeairplane;
    }

    public Airplane(String idAirplane, Typeairplane typeairplane, List<Flight> flights) {
        this.idAirplane = idAirplane;
        this.typeairplane = typeairplane;
        this.flights = flights;
    }

    public String getIdAirplane() {
        return this.idAirplane;
    }

    public void setIdAirplane(String idAirplane) {
        this.idAirplane = idAirplane;
    }

    public Typeairplane getTypeairplane() {
        return this.typeairplane;
    }

    public void setTypeairplane(Typeairplane typeairplane) {
        this.typeairplane = typeairplane;
    }

    public List<Flight> getFlights() {
        return this.flights;
    }

    public void setFlights(List<Flight> flights) {
        this.flights = flights;
    }

}
