package una.airline.domain;
// Generated May 15, 2017 11:25:46 PM by Hibernate Tools 4.3.1


import java.util.LinkedList;
import java.util.List;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private String code;
     private String name;
     private String country;
     private List<Trip> tripsForArrivalCity = new LinkedList<>();
     private List<Trip> tripsForDepartureCity = new LinkedList<>();

    public City() {
    }

	
    public City(String code, String name, String country) {
        this.code = code;
        this.name = name;
        this.country = country;
    }
    public City(String code, String name, String country, List<Trip> tripsForArrivalCity, List<Trip> tripsForDepartureCity) {
       this.code = code;
       this.name = name;
       this.country = country;
       this.tripsForArrivalCity = tripsForArrivalCity;
       this.tripsForDepartureCity = tripsForDepartureCity;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public List<Trip> getTripsForArrivalCity() {
        return this.tripsForArrivalCity;
    }
    
    public void setTripsForArrivalCity(List<Trip> tripsForArrivalCity) {
        this.tripsForArrivalCity = tripsForArrivalCity;
    }
    public List<Trip> getTripsForDepartureCity() {
        return this.tripsForDepartureCity;
    }
    
    public void setTripsForDepartureCity(List<Trip> tripsForDepartureCity) {
        this.tripsForDepartureCity = tripsForDepartureCity;
    }




}


