package una.airline.domain;
// Generated May 15, 2017 11:25:46 PM by Hibernate Tools 4.3.1



/**
 * PassengerId generated by hbm2java
 */
public class PassengerId  implements java.io.Serializable {


     private String passport;
     private int ticketNum;

    public PassengerId() {
    }

    public PassengerId(String passport, int ticketNum) {
       this.passport = passport;
       this.ticketNum = ticketNum;
    }
   
    public String getPassport() {
        return this.passport;
    }
    
    public void setPassport(String passport) {
        this.passport = passport;
    }
    public int getTicketNum() {
        return this.ticketNum;
    }
    
    public void setTicketNum(int ticketNum) {
        this.ticketNum = ticketNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PassengerId) ) return false;
		 PassengerId castOther = ( PassengerId ) other; 
         
		 return ( (this.getPassport()==castOther.getPassport()) || ( this.getPassport()!=null && castOther.getPassport()!=null && this.getPassport().equals(castOther.getPassport()) ) )
 && (this.getTicketNum()==castOther.getTicketNum());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPassport() == null ? 0 : this.getPassport().hashCode() );
         result = 37 * result + this.getTicketNum();
         return result;
   }   


}


