package una.airline.domain;
// Generated May 15, 2017 11:25:46 PM by Hibernate Tools 4.3.1



/**
 * Passenger generated by hbm2java
 */
public class Passenger  implements java.io.Serializable {


     private PassengerId id;
     private Ticket ticket;
     private String name;
     private String lastname;
     private String seat;

    public Passenger() {
    }

	
    public Passenger(PassengerId id, Ticket ticket) {
        this.id = id;
        this.ticket = ticket;
    }
    public Passenger(PassengerId id, Ticket ticket, String name, String lastname, String seat) {
       this.id = id;
       this.ticket = ticket;
       this.name = name;
       this.lastname = lastname;
       this.seat = seat;
    }
   
    public PassengerId getId() {
        return this.id;
    }
    
    public void setId(PassengerId id) {
        this.id = id;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getSeat() {
        return this.seat;
    }
    
    public void setSeat(String seat) {
        this.seat = seat;
    }




}


