package una.airline.domain;
// Generated May 15, 2017 11:25:46 PM by Hibernate Tools 4.3.1


import java.util.LinkedList;
import java.util.List;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private Integer number;
     private Flight flight;
     private User user;
     private List<Passenger> passengers = new LinkedList<>();

    public Ticket() {
    }

	
    public Ticket(Flight flight, User user) {
        this.flight = flight;
        this.user = user;
    }
    public Ticket(Flight flight, User user, List<Passenger> passengers) {
       this.flight = flight;
       this.user = user;
       this.passengers = passengers;
    }
   
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public List<Passenger> getPassengers() {
        return this.passengers;
    }
    
    public void setPassengers(List<Passenger> passengers) {
        this.passengers = passengers;
    }




}


