package una.airline.domain;
// Generated May 15, 2017 11:25:46 PM by Hibernate Tools 4.3.1


import java.util.LinkedList;
import java.util.List;

/**
 * Trip generated by hbm2java
 */
public class Trip  implements java.io.Serializable {


     private Integer idTrip;
     private City cityByArrivalCity;
     private City cityByDepartureCity;
     private int distance;
     private int duration;
     private List<Flight> flights = new LinkedList<>();

    public Trip() {
    }

	
    public Trip(City cityByArrivalCity, City cityByDepartureCity, int distance, int duration) {
        this.cityByArrivalCity = cityByArrivalCity;
        this.cityByDepartureCity = cityByDepartureCity;
        this.distance = distance;
        this.duration = duration;
    }
    public Trip(City cityByArrivalCity, City cityByDepartureCity, int distance, int duration, List<Flight> flights) {
       this.cityByArrivalCity = cityByArrivalCity;
       this.cityByDepartureCity = cityByDepartureCity;
       this.distance = distance;
       this.duration = duration;
       this.flights = flights;
    }
   
    public Integer getIdTrip() {
        return this.idTrip;
    }
    
    public void setIdTrip(Integer idTrip) {
        this.idTrip = idTrip;
    }
    public City getCityByArrivalCity() {
        return this.cityByArrivalCity;
    }
    
    public void setCityByArrivalCity(City cityByArrivalCity) {
        this.cityByArrivalCity = cityByArrivalCity;
    }
    public City getCityByDepartureCity() {
        return this.cityByDepartureCity;
    }
    
    public void setCityByDepartureCity(City cityByDepartureCity) {
        this.cityByDepartureCity = cityByDepartureCity;
    }
    public int getDistance() {
        return this.distance;
    }
    
    public void setDistance(int distance) {
        this.distance = distance;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public List<Flight> getFlights() {
        return this.flights;
    }
    
    public void setFlights(List<Flight> flights) {
        this.flights = flights;
    }




}


